<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'name' => 'Universal Paints Zinc Phosphate Quick Drying (QD) Metal Primer',
                'subtitle' => 'Universal Paints Zinc Phosphate Quick Drying (QD) Metal Primer',
                'category' => 'Protective Metal Coatings',
                'description' => '<p>Universal Paints Zinc Phosphate QD Metal Primer is an industrial-grade, fast-curing protective undercoat engineered to provide corrosion inhibition on ferrous and galvanized metal substrates. Formulated with active zinc phosphate rust-inhibiting pigments, it passivates metal surfaces to prevent rust creep under demanding environmental conditions. It dries to a smooth, uniform matt finish that establishes strong inter-coat adhesion for decorative and protective enamel topcoats.</p><h4>Key Features & Benefits:</h4><ul><li>Active Anti-Corrosive Defense: Packed with zinc phosphate pigments to combat rust and oxidation on steel and iron.</li><li>Quick-Drying Formulation (QD): Rapid drying time accelerates turnaround schedules on fabrication and maintenance projects.</li><li>Dual Color Availability: Supplied in standard Red Oxide and Black to match topcoat color profiles.</li><li>Substrate Versatility: Formulated for direct application to structural steel, ironwork, and galvanized sheets.</li><li>Optimized Adhesion & Hold-Out: Creates an anchor profile for solvent-borne decorative finishes.</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Quick-Drying Alkyd Resin with active Zinc Phosphate pigments</li><li>Finish: Smooth Matt (Available in Red Oxide and Black)</li><li>Coverage / Spreading Rate: 100 – 130 sq. ft per liter (approx. 9.3 – 12.1 m²/L) on prepared surfaces</li><li>Drying Time & Recoat Window: Touch dry in 15 – 30 minutes; recoat window after 2 – 4 hours (at 30°C ambient temperature)</li><li>Dilution / Thinner: Dilute up to a maximum of 10% by volume with Paint Thinner only (do not use water or incompatible solvents)</li><li>Pack Sizes: 4 Liters</li></ul><h4>Suitable Substrates & Applications:</h4><p>Structural iron and steel framing, purlins, trusses, beams, galvanized iron (GI) sheets, gutters, downpipes, exterior metal gates, railings, grilles, security doors, and transport equipment.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Surface Decontamination: Ensure metal is dry and clean of grease, oil, grime, scale, and surface contaminants.</li><li>Mechanical Cleaning: Chip off loose rust and mill scale. Abrade dead joints, weld seams, and rusted patches using a wire brush or sander until bright metal is exposed.</li><li>Thinning & Mixing: Stir the primer into a homogeneous suspension. Thin up to 10% with recommended thinner if needed.</li><li>Application: Apply evenly in 1 to 2 uniform coats using a brush or conventional/airless spray apparatus. Stripe-coat sharp edges and weld seams.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Ensure continuous adequate cross-ventilation. Wear safety goggles, protective gloves, and an organic vapor respirator. In case of eye contact, flush immediately with clean water and seek medical advice. Store tightly closed in a cool, dry area inaccessible to children. Lead-safe formulation (<90 ppm).</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Active Anti-Corrosive Defense", "Quick-Drying Formulation (QD)", "Dual Color Availability", "Substrate Versatility", "Optimized Adhesion & Hold-Out"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Acrylic Economy Wall Filler',
                'subtitle' => 'Universal Paints Acrylic Economy Wall Filler',
                'category' => 'Architectural Wall Preparation',
                'description' => '<p>Universal Paints Acrylic Wall Filler is an interior preparatory undercoat engineered to fill microscopic pores, hairline cracks, and surface irregularities on masonry and board substrates. It seals substrate porosity to prevent uneven absorption, cutting topcoat paint consumption while enhancing finish uniformity. Once lightly sanded, it produces an ultra-smooth, chalk-free base ready for interior emulsion systems.</p><h4>Key Features & Benefits:</h4><ul><li>Porosity Sealing & Topcoat Economy: Seals porous plaster and masonry, reducing subsequent topcoat paint consumption.</li><li>Defect & Pore Filling: Fills fine fissures, hairline crazing, and pinholes to create a uniform plane.</li><li>Effortless Sandability: Feathers down smoothly with fine sandpaper without clogging or surface tearing.</li><li>Multi-Substrate Versatility: Formulated for masonry plaster, ceiling boards, and interior plywood.</li><li>Eco-Conscious Formula: Water-based, zero added lead and mercury, low odor, and low VOC.</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Water-Based Acrylic Copolymer Emulsion</li><li>Finish: Smooth, sandable Matt White</li><li>Coverage / Spreading Rate: 120 – 180 sq. ft per liter (approx. 11.1 – 16.7 m²/L) depending on surface porosity</li><li>Drying Time & Recoat Window: Touch dry in 30 – 45 minutes; ready for sanding and topcoat application after 2 – 4 hours</li><li>Dilution / Thinner: Clean water; mix up to 25% (4 parts Wall Filler to 1 part clean water for single-coat application)</li><li>Pack Sizes: 4 Liters</li></ul><h4>Suitable Substrates & Applications:</h4><p>Interior cement plaster, rendered walls, concrete panels, gypsum boards, ceiling sheets, drywall partitions, and structural plywood.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Substrate Preparation: Verify substrate is cured, clean, sound, dry, and free of dirt, grease, or efflorescence. Scrape away loose paint.</li><li>Dilution & Mixing: Dilute with up to 25% clean potable water (4:1 ratio). Stir thoroughly until a creamy consistency is achieved.</li><li>Application: Apply a single uniform coat using a roller or masonry brush. For deeper depressions, apply an unthinned spot fill prior to full-surface coating.</li><li>Finishing: Allow 2 to 4 hours drying time. Sand with 180–220 grit paper to a smooth finish, dust off, and topcoat.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Apply in well-ventilated spaces. Avoid skin contact; rinse splashes with mild soap and water. Keep bucket tightly sealed when not in use. Formulated with no added lead and mercury (<90 ppm).</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Porosity Sealing & Topcoat Economy", "Defect & Pore Filling", "Effortless Sandability", "Multi-Substrate Versatility", "Eco-Conscious Formula"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Oil Primer Undercoat',
                'subtitle' => 'Universal Paints Oil Primer Undercoat',
                'category' => 'Protective Primers & Undercoats',
                'description' => '<p>Universal Paints Oil Primer is a solvent-borne penetrating primer and undercoat engineered for metal and timber substrates. Featuring "Locks Out Moisture, Locks In Color" barrier technology, it prevents corrosion on ferrous alloys while sealing the grain structure of timber to stop moisture ingress. It levels to a uniform foundation that maximizes the longevity, depth, and gloss retention of decorative enamel topcoats.</p><h4>Key Features & Benefits:</h4><ul><li>Moisture Barrier Technology: Seals out humidity and moisture to prevent rust development and timber decay.</li><li>Corrosion Defense: Provides an undercoat barrier over iron, steel, and galvanized metals.</li><li>Dual-Surface Compatibility: Formulated for bare exterior/interior woodwork and architectural steelwork.</li><li>Enamel Color Lock: Prevents color leaching and ensures uniform gloss retention for decorative solvent-based topcoats.</li><li>Spreading Efficiency: High-solids composition offering coverage of up to 160 sq. ft per liter.</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Long-Oil Modified Alkyd Resin / Solvent-Borne</li><li>Finish: Low-Sheen Semi-Matt Undercoat</li><li>Coverage / Spreading Rate: 150 – 160 sq. ft per liter (approx. 13.9 – 14.9 m²/L) on smooth surfaces</li><li>Drying Time & Recoat Window: Touch dry in 2 – 4 hours; full recoat window 12 – 16 hours (overnight drying recommended)</li><li>Dilution / Thinner: Mineral Turpentine only (maximum 10% dilution by volume if required; do not mix with water)</li><li>Pack Sizes: 4 Liters</li></ul><h4>Suitable Substrates & Applications:</h4><p>Ferrous sheet metal, iron gates, structural steel, galvanized components, and interior/exterior architectural timber, doors, and frames.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Surface Decontamination: Substrates must be dry and free of dirt, loose rust, grease, wax, and contaminants.</li><li>Mechanical Profiling: On metal, wire-brush or sand off all rust and scale. On timber, sand along the wood grain and wipe away dust.</li><li>Thinning & Mixing: Stir thoroughly. Thin with up to 10% Mineral Turpentine if required.</li><li>Application: Apply 1 to 2 uniform coats by brush or spray. Allow overnight dry before applying decorative topcoats.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Flammable liquid; keep away from open flames and sparks. Provide cross-ventilation. Wear protective masks and gloves. Store tightly closed in a cool, dry area away from children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Moisture Barrier Technology", "Corrosion Defense", "Dual-Surface Compatibility", "Enamel Color Lock", "Spreading Efficiency"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Water-Based Acrylic Floor Paint (Interior & Exterior)',
                'subtitle' => 'Universal Paints Water-Based Acrylic Floor Paint (Interior & Exterior)',
                'category' => 'Specialized Floor Coatings',
                'description' => '<p>Universal Paints Water-Based Floor Paint is a heavy-duty acrylic floor finish formulated to seal and protect interior and exterior masonry floors. Designed for foot-traffic resistance and environmental stability, it cures into an abrasion-resistant, semi-gloss film that shields concrete from weathering, moisture penetration, and dusting. Its water-borne chemistry provides rapid turnaround, low odor, and uniform color across indoor and outdoor floor areas.</p><h4>Key Features & Benefits:</h4><ul><li>Weather & UV Resistance: Resists weathering, UV degradation, and fading across outdoor concrete surfaces.</li><li>Abrasion Resistance: Dries to a tough, hard-wearing surface that withstands pedestrian traffic.</li><li>Rapid Walk-On Return: Touch dry in 30 minutes at 30°C, minimizing operational downtime.</li><li>Dual Interior/Exterior Performance: Suitable for indoor showrooms, utility areas, walkways, and patios.</li><li>Safety Profile: Low VOC, non-flammable water-based formula with no added lead or mercury (under 90 ppm).</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: 100% Water-Based Acrylic Polymer Floor Resin</li><li>Finish: Durable Semi-Gloss / Satin Sheen</li><li>Coverage / Spreading Rate: 80 – 90 sq. ft per liter (7.0 – 8.0 m²/L) per coat depending on concrete porosity</li><li>Drying Time & Recoat Window: Touch dry: 30 minutes; Recoat time: 4 hours minimum; Hard dry / traffic-ready: 24 hours at 30°C</li><li>Dilution / Thinner: Clean potable water up to a maximum of 10% by volume</li><li>Pack Sizes: 4 Liters</li></ul><h4>Suitable Substrates & Applications:</h4><p>Interior and exterior cement screeds, troweled concrete, paving slabs, walkways, verandahs, balconies, staircases, and domestic garages.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Curing & Moisture: Concrete must be cured minimum 4 weeks; moisture content below 10%.</li><li>Surface Cleaning: Remove oil, grease, dirt, and efflorescence. Power-wash and allow to dry completely.</li><li>Batch Blending: Intermix cans from different batches in a large container to guarantee uniform color.</li><li>Application: Apply first coat with roller or brush. After 4 hours, apply second coat perpendicularly (cross-coat).</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Maintain ventilation during application. Wash hands with soap and water. Keep container sealed in a cool, dry area away from children. Certified lead-safe (<90 ppm).</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Weather & UV Resistance", "Abrasion Resistance", "Rapid Walk-On Return", "Dual Interior/Exterior Performance", "Safety Profile"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Paint Master Polyurethane Varnish',
                'subtitle' => 'Paint Master Polyurethane Varnish',
                'category' => 'Universal Paints Wood Care Line',
                'description' => '<p>Paint Master Polyurethane Varnish by Universal Paints is a protective clear wood finish developed for interior and exterior architectural woodwork and furniture. Formulated with polyurethane resins, it forms a water-repellent, abrasion-resistant shield that highlights the natural grain of timber while defending against weathering and UV damage. Its flow and leveling properties deliver a deep, mirror-like gloss finish with durability.</p><h4>Key Features & Benefits:</h4><ul><li>Water Repellent Barrier: Forms an impervious seal that repels rain, humidity, and water ingress.</li><li>Deep Gloss Finish: Highlights the organic warmth, grain contrast, and color depth of fine timber.</li><li>UV & Weather Resistance: Resists weathering and temperature fluctuations on exterior joinery.</li><li>Tough Polyurethane Shield: Withstands surface scratching, scuffing, and routine household wear.</li><li>Professional Application Flow: Self-levels over sealed timber surfaces when applied by brush or spray.</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Premium Polyurethane Resin (Solvent-Borne)</li><li>Finish: Clear High Gloss</li><li>Coverage / Spreading Rate: 110 – 140 sq. ft per liter per coat (approx. 10.2 – 13.0 m²/L) depending on timber porosity</li><li>Drying Time & Recoat Window: Touch dry: 2 – 4 hours; Sealer coat dry: 2+ hours; Recoat window (varnish): 12 – 18 hours minimum between coats</li><li>Dilution / Thinner: Mineral Turpentine only (maximum 10% by volume if necessary)</li><li>Pack Sizes: 4 Liters</li></ul><h4>Suitable Substrates & Applications:</h4><p>Indoor and outdoor timber furniture, dining suites, hardwood doors, windows, frames, ceilings, paneling, and balustrades.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Timber Prep: Ensure wood is dry, clean, and free of resin or failed coatings. Apply preservative on exterior timber.</li><li>Sealing: Mix 1 part Sanding Sealer with 2 parts Thinner. Apply 1 to 2 coats; let dry 2 hours, sand smooth, and remove dust.</li><li>Varnishing: Stir thoroughly. Thin with up to 10% Mineral Turpentine if needed. Apply 2 full coats, allowing 12–18 hours drying between coats.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Provide cross-ventilation. Wash skin with soap and water. Keep away from direct sunlight, ignition sources, and children. Certified lead-safe.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Water Repellent Barrier", "Deep Gloss Finish", "UV & Weather Resistance", "Tough Polyurethane Shield", "Professional Application Flow"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Anti-Corrosive Matt',
                'subtitle' => 'Universal Paints Anti-Corrosive Matt',
                'category' => 'Protective Coatings',
                'description' => '<p>Universal Paints Anti-Corrosive Matt is a heavy-duty, rust-inhibiting primer specifically engineered to protect ferrous metals, galvanized steel, and steel sheets against oxidation and aggressive atmospheric degradation. Designed with the brand promise "Ruthless on Rust. Elegant on Eyes," it leaves an enduring, non-reflective matt base that dramatically enhances the adhesion and lifespan of subsequent decorative enamel topcoats.</p><h4>Key Features & Benefits:</h4><ul><li>Exceptional Rust Prevention: Chemically formulated to stop corrosion on bare and galvanized steel.</li><li>Refined Matt Finish: Non-glare undercoat texture ideal for seamless topcoat bonding.</li><li>Optimized Spreading Rate: Covers 150–160 sq. ft. per liter on smoothly prepared substrates.</li><li>Versatile Application: Formulated for smooth flow by brush or conventional spray.</li><li>Lead & Mercury Safe: Certified eco-friendly formula (<90 ppm lead).</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Solvent-based Alkyd Anti-Corrosive Primer</li><li>Finish: Matt</li><li>Coverage / Spreading Rate: 150 – 160 sq. ft. per liter</li><li>Drying Time & Recoat Window: Touch dry: 30–60 minutes; Recoat window: 4–6 hours</li><li>Dilution / Thinner: Mineral Turpentine only; reduce up to 10% if needed</li><li>Pack Sizes: 4 Liters (also available in 200 ml, 500 ml, 1 L)</li></ul><h4>Suitable Substrates & Applications:</h4><p>Structural steelwork, iron gates, window grills, galvanized iron (GI) sheets, railings, fences, and metal fabrication projects.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Surface Cleaning: Metal must be completely dry and free of dirt, oil, mill scale, and flaking rust.</li><li>Rust Removal: Wire-brush or sand heavily rusted areas down to bare metal; wipe dust free.</li><li>Mixing & Thinning: Stir thoroughly. Thin with up to 10% Mineral Turpentine if needed.</li><li>Application: Apply 2 uniform coats using a brush or spray apparatus. Finish with decorative enamel topcoat.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Work in well-ventilated spaces. Wear protective eyewear and gloves. Store tightly closed in a cool, dry area away from children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Exceptional Rust Prevention", "Refined Matt Finish", "Optimized Spreading Rate", "Versatile Application", "Lead & Mercury Safe"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters (also available in 200 ml", "price": 0}, {"size": "500 ml", "price": 0}, {"size": "1 L)", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Paint Master Floor Paint',
                'subtitle' => 'Universal Paints Paint Master Floor Paint',
                'category' => 'Paint Master',
                'description' => '<p>Universal Paints Paint Master Floor Paint is a tough, wear-resistant coating formulated on a polyurethane-modified alkyd resin system for interior masonry floors. Engineered to withstand light foot traffic, scuffs, and everyday abrasion, it provides a resilient protective barrier on both new and seasoned concrete. The quick-drying, high-coverage formulation seals porous substrates while creating a clean, durable decorative finish.</p><h4>Key Features & Benefits:</h4><ul><li>Polyurethane-Modified Toughness: High mechanical resistance against daily wear, abrasion, and chipping.</li><li>Quick-Drying Chemistry: Accelerates turnaround time for residential and light-commercial floors.</li><li>Barrier Protection: Seals concrete pores against water penetration, grease, and stains.</li><li>High Opacity & Coverage: Covers 100–130 sq. ft. per liter with outstanding leveling.</li><li>Non-Toxic: Formulated without added lead or mercury (<90 ppm).</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Polyurethane-Modified Alkyd</li><li>Finish: Durable Semi-Gloss / Satin Hard-Wear Finish</li><li>Coverage / Spreading Rate: 100 – 130 sq. ft. per liter</li><li>Drying Time & Recoat Window: Touch dry: 30–45 minutes; Recoat: 4–6 hours; Pedestrian traffic: 24 hours</li><li>Dilution / Thinner: Mineral Turpentine; add up to maximum 10%</li><li>Pack Sizes: 4 Liters (also available in 200 ml, 500 ml, 1 L)</li></ul><h4>Suitable Substrates & Applications:</h4><p>Cement floors, screeded concrete, interior walkways, verandas, basements, utility rooms, and residential garages.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Degreasing: Remove oil and grease with Mineral Turpentine and wipe dry.</li><li>Etching: For smooth concrete, etch with dilute HCl (1:5 with water) to open pores; wash thoroughly with water and allow to dry completely.</li><li>Mixing: Stir paint thoroughly; thin up to 10% with Mineral Turpentine if required.</li><li>Application: Apply 2 continuous coats with a roller or brush, respecting drying time between coats.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Ensure good cross-ventilation. Use solvent-resistant gloves and goggles. Store securely in a cool, dry area away from heat sources.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Polyurethane-Modified Toughness", "Quick-Drying Chemistry", "Barrier Protection", "High Opacity & Coverage", "Non-Toxic"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters (also available in 200 ml", "price": 0}, {"size": "500 ml", "price": 0}, {"size": "1 L)", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Paint Master Anti-Corrosive',
                'subtitle' => 'Universal Paints Paint Master Anti-Corrosive',
                'category' => 'Paint Master',
                'description' => '<p>Universal Paints Paint Master Anti-Corrosive is an industrial-grade protective metal primer formulated to halt corrosion on iron, structural steel, and galvanized metal sheets. Built upon the standard "Giving Metal a Lifetime Guarantee," it acts as an active chemical barrier to protect structural steel against moisture, oxidation, and environmental degradation. Available in a spectrum of core primer colors, it ensures an even substrate tone and long-term durability.</p><h4>Key Features & Benefits:</h4><ul><li>Lifetime Metal Defense: High-potency anti-corrosive pigments prevent rust creep and degradation.</li><li>Galvanized & Ferrous Compatibility: Excellent adhesion to both raw steel and galvanized steel sheets.</li><li>Multi-Color Selection: Available in multiple shades to simplify topcoat coverage matching.</li><li>Cost-Efficient Coverage: 120–140 sq. ft. per liter spreading efficiency.</li><li>Eco-Safe Composition: Zero added lead and mercury (<90 ppm).</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Solvent-based Synthetic Alkyd Resin</li><li>Finish: Smooth Matt / Semi-Matt Primer Finish</li><li>Coverage / Spreading Rate: 120 – 140 sq. ft. per liter</li><li>Drying Time & Recoat Window: Touch dry: 30–60 minutes; Recoat window: 4–6 hours</li><li>Dilution / Thinner: Mineral Turpentine; reduce up to 10% by volume if necessary</li><li>Pack Sizes: 4 Liters (also in 200 ml, 500 ml, 1 L)</li></ul><h4>Suitable Substrates & Applications:</h4><p>Metal gates, window frames, grates, structural beams, industrial sheds, galvanized roofing sheets, and mild steel architectural fixtures.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Pre-Cleaning: Surface must be dry and free of dirt, oil, and moisture.</li><li>Rust Removal: Scrape and abrade loose rust and scale using wire brush or sandpaper down to sound metal.</li><li>Mixing: Stir paint thoroughly; thin with up to 10% Mineral Turpentine if necessary.</li><li>Application: Apply 1 to 2 coats as undercoat before finishing with decorative topcoat.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Keep workspace well-ventilated. Wear safety goggles and gloves. Store in dry, well-ventilated conditions out of reach of children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Lifetime Metal Defense", "Galvanized & Ferrous Compatibility", "Multi-Color Selection", "Cost-Efficient Coverage", "Eco-Safe Composition"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters (also in 200 ml", "price": 0}, {"size": "500 ml", "price": 0}, {"size": "1 L)", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Hybrid Aquamax Waterproofing',
                'subtitle' => 'Universal Paints Hybrid Aquamax Waterproofing',
                'category' => 'Hybrid Technology Line',
                'description' => '<p>Universal Paints Hybrid Aquamax is a high-performance elastomeric waterproofing barrier built on advanced hybrid polymer technology to eliminate water ingress on vertical and horizontal structures. Rigorously tested and certified by the Industrial Technology Institute (ITI), it features 100% elongation elasticity to bridge expanding and contracting hairline cracks. It functions both as an adhesion primer and a resilient waterproofing shield for exterior masonry, concrete roofs, and water containment tanks.</p><h4>Key Features & Benefits:</h4><ul><li>ITI Certified Performance: Tested and certified by the Industrial Technology Institute (ITI).</li><li>100% Elongation Membrane: Stretches across hairline cracks to prevent water seepage under thermal movement.</li><li>Dual-Action Formulation: Functions as both an integral primer and a waterproof topcoat.</li><li>Water Tank Safe: Suitable for sealing small domestic water tanks, ponds, and reservoirs.</li><li>Weather & UV Shield: Protects exterior walls and asbestos sheets against tropical downpours and solar degradation.</li><li>Eco-Friendly & Safe: Water-based, low VOC, and free of added lead and mercury (<90 ppm).</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Water-Based Hybrid Elastomeric Polymer</li><li>Finish: Smooth Low-Sheen / Satin Waterproof Membrane</li><li>Coverage / Spreading Rate: 40 – 50 sq. ft. per liter (dependent on surface roughness)</li><li>Drying Time & Recoat Window: Walls: Surface dry: 15–30 min; Recoat: 2–3 hours; Full cure: 24 hours. Water Tanks: Surface dry: 15 min; Full immersion cure: mandatory 72 hours before filling.</li><li>Dilution / Thinner: Clean water; Walls: Dilute first coat up to 25% water; apply second coat undiluted. Water Tanks: First coat diluted; second coat 100% undiluted.</li><li>Pack Sizes: 4 Liters (also available in 1 L, 10 L, 20 L)</li></ul><h4>Suitable Substrates & Applications:</h4><p>Exterior masonry walls, concrete flat roofs, parapet walls, asbestos cement sheets, retaining walls, and small domestic water tanks. (Do not apply over interior wall putty).</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Surface Washing: Clean surfaces thoroughly with high-pressure water jet to remove algae, moss, and dirt.</li><li>Defect Repair: Seal structural cracks with repair mortar. Ensure surface is free of interior putty.</li><li>Wall Application: Dilute first coat with 25% water and apply horizontally. After 2–3 hours, apply second coat vertically with minimal water.</li><li>Water Tank Application: Apply thinned prime coat, followed by undiluted second coat. Leave to dry 72 hours before filling.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Apply in well-ventilated areas. Wear safety glasses and rubber gloves. Store tightly sealed in a cool, dry area away from children. Non-flammable waterborne formula.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["ITI Certified Performance", "100% Elongation Membrane", "Dual-Action Formulation", "Water Tank Safe", "Weather & UV Shield", "Eco-Friendly & Safe"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters (also available in 1 L", "price": 0}, {"size": "10 L", "price": 0}, {"size": "20 L)", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Premium Wall Filler',
                'subtitle' => 'Universal Paints Premium Wall Filler',
                'category' => 'Architectural Undercoats & Fillers',
                'description' => '<p>Universal Paints Premium Wall Filler is a premium interior preparatory undercoat formulated to seal fine masonry cracks, plaster voids, and surface scratches following putty application. Guided by the philosophy "Where Quality Meets Smoothness," it levels irregularities on interior substrates to produce a uniform, ready-to-paint foundation. By regulating substrate porosity, it reduces topcoat absorption, lowering the paint volume needed for finish coats.</p><h4>Key Features & Benefits:</h4><ul><li>Quality & Smoothness: Conceals hairline shrinkage cracks and sand marks from putty cutting.</li><li>Reduces Paint Consumption: Uniformly seals porosity to prevent excessive absorption.</li><li>Single-Coat Coverage: High hiding power when thinned with up to 25% clean water.</li><li>Effortless Sanding: Formulated for fine dry-sanding with 240-grade sandpaper.</li><li>Broad Versatility: Bonds smoothly to plaster, ceilings, drywall, and engineered boards.</li><li>Lead-Free: Zero added lead or mercury (<90 ppm).</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Water-Based Acrylic Copolymer Filler</li><li>Finish: Smooth Matt White</li><li>Coverage / Spreading Rate: 120 – 150 sq. ft. per liter</li><li>Drying Time & Recoat Window: Touch dry: 20–30 min; Sanding window: 2–3 hours; Topcoat recoat: 3–4 hours</li><li>Dilution / Thinner: Clean water; mix 4 parts filler with 1 part water (up to 25% clean water)</li><li>Pack Sizes: 4 Liters (also available in 1 L, 10 L, 20 L)</li></ul><h4>Suitable Substrates & Applications:</h4><p>Interior masonry walls, plastered ceilings, gypsum boards, drywall partitions, and plywood surfaces.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Substrate Prep: Ensure masonry and putty are cured, stable, dry, and clean.</li><li>Dilution & Mixing: Stir thoroughly. Add up to 25% clean water (4:1 mix) and stir until uniform.</li><li>Application: Apply 1 even coat using roller or brush.</li><li>Sanding & Dusting: Allow 2–3 hours drying time; smooth with 240-grade sandpaper and wipe dust free before topcoating.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Ensure good ventilation. Wear a dust mask and safety goggles when sanding. Store securely closed and out of reach of children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Quality & Smoothness", "Reduces Paint Consumption", "Single-Coat Coverage", "Effortless Sanding", "Broad Versatility", "Lead-Free"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters (also available in 1 L", "price": 0}, {"size": "10 L", "price": 0}, {"size": "20 L)", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paint Master Gloss Enamel',
                'subtitle' => 'Universal Paint Master Gloss Enamel',
                'category' => 'Paint Master',
                'description' => '<p>Universal Paint Master Gloss Enamel is a premium-grade, synthetic solvent-based alkyd finish formulated to provide superior protection and rich decorative color to interior and exterior surfaces. Designed for outstanding durability and scrub resistance, it forms a tough, mirror-like gloss barrier that shields surfaces against everyday wear, moisture, and stains. It is the premier protective coating for architectural woodwork, architectural steelwork, and cured masonry.</p><h4>Key Features & Benefits:</h4><ul><li>Brilliant High-Gloss Finish: Delivers a lustrous, mirror-smooth sheen that enhances woodwork and metal fixtures.</li><li>Weather & Abrasion Resistance: Resists peeling, cracking, moisture, and mechanical abrasion.</li><li>Multi-Substrate Versatility: Seamlessly adheres to treated timber, structural steel, wrought iron, and primed concrete.</li><li>Non-Toxic: Formulated with no added lead or mercury (<90 ppm).</li><li>Superior Film Integrity: Delivers solid hiding power and excellent flow and leveling.</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Solvent-based Synthetic Alkyd Resin</li><li>Finish: High Gloss</li><li>Coverage / Spreading Rate: 140 – 160 sq. ft. per liter per coat</li><li>Drying Time & Recoat Window: Recoat interval: minimum 6–8 hours; Full cure: 24 hours</li><li>Dilution / Thinner: Thin up to 10% with Mineral Turpentine only</li><li>Pack Sizes: 4 Liters (also available in 200 ml, 500 ml, 1 Liter)</li></ul><h4>Suitable Substrates & Applications:</h4><p>Interior and exterior architectural woodwork, doors, frames, paneling, metalwork, gates, railings, steel window frames, and cured primed masonry.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Cleaning: Substrates must be dry and cleaned of grease, oil, rust, grime, and wax.</li><li>Priming: Apply Aluminium Wood Primer on timber. On metal, wire-brush rust and apply anti-corrosive primer. On masonry, cure 28 days and spot-prime.</li><li>Application: Stir thoroughly. Blend cans from different batches together. Apply 2 coats by brush, roller, or spray with 6–8 hours drying between coats.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Work in well-ventilated areas. Wear safety glasses and solvent-resistant gloves. Flammable liquid: store away from heat sources and children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Brilliant High-Gloss Finish", "Weather & Abrasion Resistance", "Multi-Substrate Versatility", "Non-Toxic", "Superior Film Integrity"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters (also available in 200 ml", "price": 0}, {"size": "500 ml", "price": 0}, {"size": "1 Liter)", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paint Master Interior Emulsion',
                'subtitle' => 'Universal Paint Master Interior Emulsion',
                'category' => 'Paint Master',
                'description' => '<p>Universal Paint Master Interior Emulsion is a premium water-based wall coating engineered to provide outstanding value, durability, and vibrant interior aesthetics. Formulated with a specialized acrylic polymer matrix, it locks in rich pigmentation to keep interior living spaces pristine and colorful over time. Its quick-drying performance significantly reduces turnaround time for residential, commercial, and institutional renovation projects.</p><h4>Key Features & Benefits:</h4><ul><li>Rapid Drying: Touch dry in 15–20 minutes, allowing fast multi-coat applications and same-day occupancy.</li><li>Vibrant Color Retention: Polymer-locked pigments protect against fading and yellowing.</li><li>High Value & Coverage: Covers up to 140 sq. ft. per liter with outstanding opacity.</li><li>Eco-Safe & Low Odor: Zero added lead or mercury (<90 ppm).</li><li>Smooth Matte Leveling: Hides minor plaster imperfections with a velvety finish.</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Water-based Modified Acrylic Copolymer Emulsion</li><li>Finish: Smooth Matt</li><li>Coverage / Spreading Rate: 120 – 140 sq. ft. per liter per coat</li><li>Drying Time & Recoat Window: Touch dry: 15–20 min; Recoat window: 3–4 hours; Full cure: 24 hours</li><li>Dilution / Thinner: Clean potable water; dilute up to 25% by volume</li><li>Pack Sizes: 4 Liters (also available in 1 L, 10 L, 20 L)</li></ul><h4>Suitable Substrates & Applications:</h4><p>Interior walls, ceilings, corridors, cement plaster, concrete, gypsum boards, skimmed plasterboard, and brickwork.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Surface Prep: Ensure substrate is clean, dry, and sound. Repair cracks with Wall Putty followed by Acrylic Wall Filler.</li><li>Priming: On fresh or alkaline plaster, apply Alkali-Resistant Wall Primer and cure 24 hours.</li><li>Mixing: Stir thoroughly before adding water. Thin up to 25% with clean water. Intermix cans from different batches.</li><li>Application: Apply 2 to 3 coats using brush or roller. Allow 3 to 4 hours drying between coats.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Ensure cross-ventilation. Wear protective eyewear and gloves. Store in a cool, shaded space away from children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Rapid Drying", "Vibrant Color Retention", "High Value & Coverage", "Eco-Safe & Low Odor", "Smooth Matte Leveling"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters (also available in 1 L", "price": 0}, {"size": "10 L", "price": 0}, {"size": "20 L)", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Appco Aqua Flex 3-in-1 Exterior Waterproofing Paint',
                'subtitle' => 'Universal Paints Appco Aqua Flex 3-in-1 Exterior Waterproofing Paint',
                'category' => 'Appco',
                'description' => '<p>Universal Paints Appco Aqua Flex is an advanced 3-in-1 high-build elastomeric waterproofing coating designed to shield exterior masonry against driving rain, moisture seepage, and severe tropical weather. It cures into a flexible, seamless membrane that bridges hairline cracks while repelling exterior liquid water. Formulated with potent anti-microbial additives, it continuously defends exterior facades against algae, fungal, and moss infestations.</p><h4>Key Features & Benefits:</h4><ul><li>Triple-Action 3-in-1 Defense: Acts as an exterior paint, crack bridging seal, and waterproof barrier.</li><li>Elastomeric Crack Bridging: Bridges dynamic hairline cracks to prevent rainwater intrusion.</li><li>Superior Algae & Fungi Resistance: Impregnated with bio-stabilizers to inhibit mold and lichen.</li><li>Cross-Coat Reinforcement: Applied horizontally for base coat and vertically for top coat for seamless barrier.</li><li>Lead & Mercury Free: Zero added lead or mercury (<90 ppm).</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: High-Solids Elastomeric Pure Acrylic Waterproofing Polymer</li><li>Finish: Low Sheen / Satin Elastomeric Protective Film</li><li>Coverage / Spreading Rate: 40 – 50 sq. ft. per liter for a complete 2-coat system</li><li>Drying Time & Recoat Window: Recoat interval: 2–3 hours between coats; Full waterproof cure: 24 hours</li><li>Dilution / Thinner: Clean water; thin first coat up to 25%, thin second coat up to 10%</li><li>Pack Sizes: 4 Liters (also available in 1 L, 10 L, 20 L)</li></ul><h4>Suitable Substrates & Applications:</h4><p>Exterior facades, parapets, roof gutters, balconies, concrete slabs, cement-rendered walls, stone facades, and asbestos sheeting.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Surface Prep: Wash masonry with high-pressure water jet to remove algae, moss, and dirt. Ensure dry surface.</li><li>First Coat (Horizontal): Thin with 25% water. Apply horizontally across substrate; allow 2–3 hours to dry.</li><li>Second Coat (Vertical): Thin with 10% water. Apply vertically at 90° to the first coat. Allow 24 hours for full cure.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Wear goggles and gloves. Flush eye splashes with running water. Store upright in a cool, dry area away from children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Triple-Action 3-in-1 Defense", "Elastomeric Crack Bridging", "Superior Algae & Fungi Resistance", "Cross-Coat Reinforcement", "Lead & Mercury Free"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters (also available in 1 L", "price": 0}, {"size": "10 L", "price": 0}, {"size": "20 L)", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Superlux Weather Proof Paint',
                'subtitle' => 'Universal Paints Superlux Weather Proof Paint',
                'category' => 'Superlux',
                'description' => '<p>Universal Paints Superlux Weather Proof Paint is a heavy-duty exterior acrylic emulsion specifically engineered to withstand harsh ultraviolet radiation, intense tropical heat, and heavy rainfall. Formulated with high-grade, lightfast inorganic pigments, it maintains color brilliance and resists chalking or fading under prolonged sunlight. Active anti-microbial biocide chemistry prevents mold, lichen, and algae growth, preserving the pristine architectural appearance of exterior walls for years.</p><h4>Key Features & Benefits:</h4><ul><li>Sunlight & UV Resistance: Resists photochemical degradation and color fading under sunlight.</li><li>Biological Defense: Anti-fungal and anti-algal compounds prevent black mold and green algae stains.</li><li>Weather-Shielding Acrylic: Breathable, water-resistant protective barrier that flexes with temperature changes.</li><li>Single-Coat High-Build: Supports rapid single-coat application when thinned up to 25% on sound painted walls.</li><li>Safe & Certified: Zero added lead and mercury (<90 ppm).</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: 100% Exterior Acrylic Binder Emulsion</li><li>Finish: Smooth Low Sheen / Exterior Matt</li><li>Coverage / Spreading Rate: 100 – 110 sq. ft. per liter per coat</li><li>Drying Time & Recoat Window: Touch dry: 30–45 min; Recoat: 2–3 hours; Full cure: 24 hours</li><li>Dilution / Thinner: Clean potable water; dilute up to 25% by volume</li><li>Pack Sizes: 4 Liters (also available in 1 L, 10 L, 20 L)</li></ul><h4>Suitable Substrates & Applications:</h4><p>Exterior concrete walls, cement-sand plasters, precast panels, boundary walls, brickwork, and masonry blocks.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Substrate Inspection: Plaster must be cured 28 days and dry. Pressure wash to remove algae and mildew.</li><li>Priming: Apply Masonry Sealer on powdery walls. On standard plaster, apply Weather Shield Crack Bridging Wall Primer (or exterior wall filler).</li><li>Application: Mix paint, thin up to 25% with water, and blend batches. Apply 2 to 3 uniform coats with roller or brush. Allow 2–3 hours between coats.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Store in a cool, shaded area away from children. Wear eye protection and gloves. Wash splashes immediately with clean water.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Sunlight & UV Resistance", "Biological Defense", "Weather-Shielding Acrylic", "Single-Coat High-Build", "Safe & Certified"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters (also available in 1 L", "price": 0}, {"size": "10 L", "price": 0}, {"size": "20 L)", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Superlux Interior Emulsion',
                'subtitle' => 'Universal Paints Superlux Interior Emulsion',
                'category' => 'Superlux',
                'description' => '<p>Universal Paints Superlux Interior Emulsion is an economical, high-coverage interior wall paint engineered to deliver optimal value for money without sacrificing aesthetic quality. Formulated for residential homes, apartment complexes, and commercial properties, it creates an elegant, uniform matte finish that hides surface imperfections. It provides long-lasting durability, dependable opacity, and color richness comparable to premium emulsion paints.</p><h4>Key Features & Benefits:</h4><ul><li>Cost-Effective Premium Appearance: High-opacity coverage and smooth texture at an accessible price.</li><li>Simple 4:1 Dilution: Mixes easily with 25% clean water (4 parts paint to 1 part water).</li><li>Wall Protection: Forms a durable film that protects against daily dusting and scuffing.</li><li>Fast Recoating: Recoatable in just 2 to 3 hours.</li><li>Safe & Lead-Free: Zero added lead or heavy metals (<90 ppm).</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Water-based Acrylic Copolymer Emulsion</li><li>Finish: Smooth Matte</li><li>Coverage / Spreading Rate: 100 – 120 sq. ft. per liter per coat</li><li>Drying Time & Recoat Window: Touch dry: 30 min; Recoat: 2–3 hours; Full cure: 24 hours</li><li>Dilution / Thinner: Clean water; dilute 25% (4:1 mix)</li><li>Pack Sizes: 4 Liters (also available in 1 L, 10 L, 20 L)</li></ul><h4>Suitable Substrates & Applications:</h4><p>Interior walls, partition walls, and ceilings in residential and commercial properties; cement plaster, concrete, drywall, and brickwork.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Surface Prep: Substrate must be clean, dry, and sound. Fill cracks with Wall Putty and Acrylic Wall Filler; sand smooth.</li><li>Priming: Apply Alkali-Resistant Plaster Primer on new plaster and allow 24 hours to cure.</li><li>Mixing: Stir paint, add 25% clean water, and blend multiple batches together.</li><li>Application: Apply 2 to 3 coats with brush or roller. Allow 2–3 hours drying time between coats.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Ensure good ventilation. Wear protective eyewear and gloves. Store in a cool, dry area out of reach of children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Cost-Effective Premium Appearance", "Simple 4", "Wall Protection", "Fast Recoating", "Safe & Lead-Free"]', true),
                'pack_sizes' => json_decode('[{"size": "4 Liters (also available in 1 L", "price": 0}, {"size": "10 L", "price": 0}, {"size": "20 L)", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'UPI Chinese Lacquer',
                'subtitle' => 'UPI Chinese Lacquer',
                'category' => 'UPI Decorative Specialties',
                'description' => '<p>UPI Chinese Lacquer is a high-grade synthetic decorative enamel lacquer formulated for small-scale metal, craft, and timber applications. It delivers a rich, mirror-like high-gloss finish that protects surfaces from everyday wear, moisture, and mild abrasion. Ideal for ornamental ironwork, furniture accents, handicraft projects, and quick surface restorations requiring vibrant, durable color depth.</p><h4>Key Features & Benefits:</h4><ul><li>Brilliant High-Gloss Lustre: Imparts a deep, reflective enamel sheen to decorative items.</li><li>Fast Air-Drying: Sets quickly to minimize dust pickup and speed up project turnaround.</li><li>Durable Film Hardness: Resists chipping, scratching, and household handling once cured.</li><li>Smooth Flow & Leveling: Spreads evenly without brush marks.</li><li>Extensive Shade Selection: Available in White, Black, Red, Blue, Light Blue, Yellow, Pink, Green, Brown, Golden Brown, Gold, and Silver.</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Synthetic Alkyd / Nitrocellulose-modified resin blend</li><li>Finish: High Gloss / Lustrous Sheen</li><li>Coverage / Spreading Rate: ~12 – 14 sq. ft per 50 ml container</li><li>Drying Time & Recoat Window: Touch dry: 15–30 minutes; Hard dry / recoatable: 2–4 hours</li><li>Dilution / Thinner: Ready to use; thin up to 5%–10% with NC Thinner or mineral turpentine if necessary</li><li>Pack Sizes: 50 ml (Small Embossed Tin), 100 ml</li></ul><h4>Suitable Substrates & Applications:</h4><p>Decorative metal crafts, wrought iron grilles, bicycles, toys, picture frames, architectural timber models, wood carvings, signboards, pottery, and domestic hardware touch-ups.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Cleaning: Clean, dry substrate free of oil, grease, and dust.</li><li>Abrasion & Priming: Sand bare wood smooth; apply anti-corrosive primer on bare ferrous metals.</li><li>Application: Stir thoroughly. Apply 1 to 2 thin coats with a fine soft-hair brush or hobby airbrush.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Flammable liquid. Use in well-ventilated areas away from heat and open flames. Wear gloves and eye protection. Keep out of reach of children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Brilliant High-Gloss Lustre", "Fast Air-Drying", "Durable Film Hardness", "Smooth Flow & Leveling", "Extensive Shade Selection"]', true),
                'pack_sizes' => json_decode('[{"size": "50 ml (Small Embossed Tin)", "price": 0}, {"size": "100 ml", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Microglaze Anti Corrosive',
                'subtitle' => 'Microglaze Anti Corrosive',
                'category' => 'Microglaze Series',
                'description' => '<p>Microglaze Anti Corrosive is an industrial-grade protective primer and coating engineered to arrest rust and shield structural ferrous metals from environmental degradation. It combines active rust-inhibitive pigmentation with a weather-resistant alkyd binder to produce a durable, moisture-repellent barrier. The cured film delivers a clean gloss sheen that protects exterior and interior steelwork against humid and tropical climates.</p><h4>Key Features & Benefits:</h4><ul><li>Corrosion Inhibition: Active anti-corrosive compounds passivate metal surfaces and halt rust creep.</li><li>Robust Weather Shield: Protects steelwork from rain, high humidity, and solar degradation.</li><li>Dual Action Protection: Functions as a primer or standalone anti-corrosive gloss finish.</li><li>Superior Adhesion: Tenacious bond on mild steel, galvanized sheets, and welded joints.</li><li>Economical Coverage: 110–140 sq. ft per liter spreading efficiency.</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Synthetic Alkyd Resin with active anti-rust pigments</li><li>Finish: Gloss / Sheen</li><li>Coverage / Spreading Rate: 110 – 140 sq. ft per liter (approx. 10 – 13 m²/L)</li><li>Drying Time & Recoat Window: Touch dry: 30–45 min; Handle dry: 2–3 hours; Recoat: 6–8 hours</li><li>Dilution / Thinner: Ready to use; thin up to 5%–10% with mineral turpentine or paint thinner if needed</li><li>Pack Sizes: 200 ml, 500 ml, 1 Liter, 4 Liters</li></ul><h4>Suitable Substrates & Applications:</h4><p>Structural steel beams, roof trusses, gates, railings, window grills, galvanized sheets, storage tanks, and agricultural machinery.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Cleaning: Degrease metal thoroughly with solvent to remove oil, dirt, and cutting lubricants.</li><li>Rust Removal: Remove loose rust, mill scale, and welding slag using a wire brush or sander.</li><li>Application: Stir thoroughly. Apply 1 to 2 uniform coats with brush, roller, or spray gun. Ensure full film build over weld seams.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Flammable product; keep away from open flames. Ensure continuous cross-ventilation. Wear solvent-resistant gloves and goggles. Store in a cool, elevated area away from children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Corrosion Inhibition", "Robust Weather Shield", "Dual Action Protection", "Superior Adhesion", "Economical Coverage"]', true),
                'pack_sizes' => json_decode('[{"size": "200 ml", "price": 0}, {"size": "500 ml", "price": 0}, {"size": "1 Liter", "price": 0}, {"size": "4 Liters", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Microglaze QD Metal Primer (Zinc Phosphate)',
                'subtitle' => 'Microglaze QD Metal Primer (Zinc Phosphate)',
                'category' => 'Microglaze Series',
                'description' => '<p>Microglaze QD Metal Primer is a fast-drying, zinc phosphate-fortified anti-rust primer engineered for rapid shop and field priming of ferrous metals. It chemically passivates steel, iron, and galvanized surfaces to prevent oxidation and undercut corrosion while establishing an adhesive foundation for topcoats. Dries to a smooth, uniform matt film that optimizes inter-coat bonding with synthetic enamels and industrial finishes.</p><h4>Key Features & Benefits:</h4><ul><li>Active Zinc Phosphate Chemistry: Provides sacrificial and barrier corrosion protection across ferrous metals and galvanized sheets.</li><li>Quick-Drying (QD): Rapid drying streamlines shop fabrication and minimizes handling downtime.</li><li>Enhanced Recoat Adhesion: Matt tooth anchors synthetic enamel topcoats.</li><li>Weld Joint Protection: Seals ground welds, cut edges, and seams against moisture.</li><li>Available Shades: Supplied in Red Oxide and Black formulations.</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Quick-Drying Modified Alkyd Resin with Zinc Phosphate</li><li>Finish: Smooth Matt</li><li>Coverage / Spreading Rate: 100 – 140 sq. ft per liter</li><li>Drying Time & Recoat Window: Touch dry: 15–20 minutes; Recoat window: 2–3 hours</li><li>Dilution / Thinner: Stir well; thin up to 10% with high-grade Thinner if required</li><li>Pack Sizes: 200 ml, 500 ml, 1 Liter, 4 Liters</li></ul><h4>Suitable Substrates & Applications:</h4><p>Steel structures, iron fabrications, galvanized iron (GI) surfaces, sheet metal components, vehicle chassis, machinery framing, and pipelines.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Surface Prep: Degrease metal to remove oils, dirt, and dust. Clear rust scale with wire brush or abrasive disc.</li><li>Mixing: Stir thoroughly. Add up to 10% thinner if needed for spray or fine brushing.</li><li>Application: Apply evenly by brush or spray at 100–140 sq. ft/L. Allow 2–3 hours drying before applying enamel topcoats.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Maintain adequate ventilation. Wear safety goggles and vapor respirators. Wash eye contact with soap and water; consult a doctor. Store in a dry, covered area away from children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Active Zinc Phosphate Chemistry", "Quick-Drying (QD)", "Enhanced Recoat Adhesion", "Weld Joint Protection", "Available Shades"]', true),
                'pack_sizes' => json_decode('[{"size": "200 ml", "price": 0}, {"size": "500 ml", "price": 0}, {"size": "1 Liter", "price": 0}, {"size": "4 Liters", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Slab Seal Waterproofing Compound',
                'subtitle' => 'Universal Paints Slab Seal Waterproofing Compound',
                'category' => 'Slab Seal Construction Chemicals',
                'description' => '<p>Universal Paints Slab Seal is an elastomeric, two-component acrylic polymer-modified cementitious waterproofing system engineered to prevent water ingress across concrete and masonry structures. Comprising a pre-measured reactive powder and liquid polymer, it chemically reacts upon mixing to form a monolithic, flexible membrane that accommodates thermal movement. Ideal for flat roofs, wet areas, and external foundations, offering weather-resilient protection that can be applied directly to damp substrates.</p><h4>Key Features & Benefits:</h4><ul><li>Dual-Component System: Combines cementitious compressive strength with polymer elasticity to bridge hairline cracks.</li><li>Moisture-Tolerant Application: Applied directly over pre-wetted/saturated concrete surfaces, thriving in humid climates.</li><li>Hydrostatic Pressure Resistance: Forms an impermeable barrier that withstands ponding water.</li><li>Plaster Key Capability: Accepts coarse sand broadcast onto wet second coat to form a mechanical key for plaster or screed.</li><li>Water Cleanable: Easily mixed without added water; applied with a masonry block brush.</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Two-part Acrylic Polymer-Modified Cementitious Slurry (Part A: Powder, Part B: Liquid Polymer)</li><li>Finish: Uniform Textured Cementitious Membrane</li><li>Coverage / Spreading Rate: 8 – 10 sq. ft per kg (1.0 – 1.2 mm dry film thickness across 2 coats; ~38–47 sq. ft per 4.7 kg kit)</li><li>Drying Time & Recoat Window: Apply second coat once first is "dry tacky" (2–4 hours); full water cure in 5–7 days</li><li>Dilution / Thinner: Do NOT add water. Mix strictly at 5:3 (w/w) Powder : Polymer Liquid ratio</li><li>Pack Sizes: 1 Kg, 4.7 Kg (nominal 4 Kg label class), 10 Kg, 20 Kg, 36 Kg</li></ul><h4>Suitable Substrates & Applications:</h4><p>Reinforced concrete roof slabs, balconies, terraces, sunken bathroom slabs, shower stalls, water tanks, basements, retaining walls, and footings.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>Substrate Prep: Remove algae, laitance, oil, and loose concrete. Pre-wet substrate to Saturated Surface Dry (SSD) condition.</li><li>Mixing: Pour liquid into clean bucket; gradually add powder while mixing with paddle mixer until creamy mortar consistency is reached.</li><li>Application: Apply 2 coats with stiff masonry brush. Apply second coat perpendicular (90°) to first coat when dry-tacky. Broadcast coarse sand on wet second coat if plastering over.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Alkaline cementitious product. Wear gloves, goggles, and protective clothing. Flush skin/eyes immediately with fresh water. Store in cool, elevated conditions out of direct sunlight. 12-month shelf life.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Dual-Component System", "Moisture-Tolerant Application", "Hydrostatic Pressure Resistance", "Plaster Key Capability", "Water Cleanable"]', true),
                'pack_sizes' => json_decode('[{"size": "1 Kg", "price": 0}, {"size": "4.7 Kg (nominal 4 Kg label class)", "price": 0}, {"size": "10 Kg", "price": 0}, {"size": "20 Kg", "price": 0}, {"size": "36 Kg", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
            [
                'name' => 'Universal Paints Sudo Sudu Premium Emulsion',
                'subtitle' => 'Universal Paints Sudo Sudu Premium Emulsion',
                'category' => 'UPI Premium Architectural Emulsion',
                'description' => '<p>UPI "Sudho Sudu" Brilliant White is a high-opacity, eco-friendly interior wall emulsion designed to impart an ultra-white, luminous ambiance to living spaces. Formulated with premium acrylic binders and pure light-reflecting titanium dioxide pigments, it provides uniform coverage and long-lasting color purity. Suitable for high-traffic domestic and commercial interiors, delivering a smooth velvet-matt finish that offers excellent value for money.</p><h4>Key Features & Benefits:</h4><ul><li>Ultra-Luminous "Sudo Sudu" White: Maximizes light reflectance and brilliant white aesthetics.</li><li>High Spreading Capacity: 180 – 225 sq. ft per liter, optimizing cost efficiency.</li><li>Eco-Conscious Formulation: Water-based, low VOC with minimal odor.</li><li>Rapid Touch-Dry: Sets touch-dry in 15–20 minutes, allowing fast recoating.</li><li>Smooth Surface Uniformity: Blends smoothly over acrylic fillers to hide subtle wall defects.</li></ul><h4>Technical Specifications:</h4><ul><li>Base / Chemistry: Water-Based Acrylic Copolymer Emulsion with premium white pigments</li><li>Finish: Smooth Velvet Matt / Flat Finish</li><li>Coverage / Spreading Rate: 180 – 225 sq. ft per liter depending on substrate porosity</li><li>Drying Time & Recoat Window: Touch dry: 15–20 min; Recoat interval: minimum 4 hours</li><li>Dilution / Thinner: Thin with up to 25% clean potable water</li><li>Pack Sizes: 1 Liter, 4 Liters, 10 Liters, 20 Liters</li></ul><h4>Suitable Substrates & Applications:</h4><p>Interior walls, ceilings, masonry, brickwork, gypsum plasterboards, cement rendering, and fiber-cement boards.</p><h4>Surface Preparation & Application Guide:</h4><ol><li>New Surfaces: Clean surface, fill cracks with Wall Putty and Acrylic Wall Filler. Apply Alkali Resistant Plaster Primer on new/alkaline plaster and dry 24 hours.</li><li>Previously Painted: Wash down with mild detergent. Scrape loose paint. Sand smooth and dust off. Prime powdery walls with masonry sealer.</li><li>Thinning & Mixing: Dilute with up to 25% clean water and stir thoroughly.</li><li>Application: Apply 2 to 3 uniform coats with brush, roller, or spray. Maintain 4 hours drying time between coats. Clean tools with water.</li><h4>Health, Safety & Environmental Guidelines:</h4><p>Wear gloves to prevent skin sensitivity. In case of eye contact, rinse immediately with water and seek medical advice. Do not release paint residue into waterways. Keep out of reach of children.</p>',
                'price_min' => 1500,
                'price_max' => 20000,
                'rating' => '4.8',
                'reviews' => rand(10, 200),
                'features' => json_decode('["Ultra-Luminous \"Sudo Sudu\" White", "High Spreading Capacity", "Eco-Conscious Formulation", "Rapid Touch-Dry", "Smooth Surface Uniformity"]', true),
                'pack_sizes' => json_decode('[{"size": "1 Liter", "price": 0}, {"size": "4 Liters", "price": 0}, {"size": "10 Liters", "price": 0}, {"size": "20 Liters", "price": 0}]', true),
                'colors' => [],
                'main_image' => '/images/home-page/wood.jpg',
                'is_best_seller' => true,
                'is_in_stock' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
